[Variables]
colormeasure_x=0

[Metadata]
Name=Fedina\\Color Measure
Author=reddit.com/u/khanhas
Description=Contain a universal script for all module can get its color based on its position. 

[ColorMeasureScript]
Measure=Script
ScriptFile=#ROOTCONFIGPATH#Themes\#Theme#\Additional_Comps_And_Scripts\script_ModuleColor.lua
;Use this variable to get module color
;[ColorMesureScript:GetColor(color1, color2, direction, position)] 
;    color1, color2 (hex): wrap them in pair of single quote ' '
;    direction: 'side to middle', 'middle to side', 'left to right', 'right to left'
;    position: module position X variables or any number you want
