[Variables]
Bar_Opacity=00
Bar_Width =1920
Bar_Height =40
Bar_OffsetX =0
Bar_OffsetY =12

Section_Height =40
Section_Padding = 12

Color_Scheme1 =15222B
Color_Scheme2 =FFF3E6
Color_Scheme3 =232F36
Color_Scheme4 =25B3A4
Color_Scheme5 =FFFFFF

Font_Face1=PixelMPlus12
Font_Face2=Balthasar Regular NBP
Font_Size=9

Shadow=0
Translucent=0
DefaultAddedModules=startmenu,workspacemanager,tray,music,time,date,volume,taskbar,weather

